### ISSUE TITLE
Estado Previo Carga Datos Usuario

### ISSUE THREAD

**Issue by jonstm** [bisite/Ebikemotion2-iOSFeedback#1]
## Platform Information

* Application:

> - [X] Ebikemotion 2

* Version: 1.0.2

* Build Number: 687.170320

* Source:

> - [X] Buddybuild

* Device: iPhone 6

* iOS Version:  iOS 10.2.1

* Internet Connectivity: 4G

* iWoc Firmware Version (if any): 

> - [ ] CAN
> - [ ] 485

## Current Behavior
Al acceder por primera vez y poca cobertura en ese sitio, se ve claramente en el nombre de usuario del perfil "John Connors" que era el ejemplo que pusimos

## Possible Solution
Permanecer sin contenido alguno hasta que se produzca la carga de los datos del usuario.

**Comment by minuscorp** [comment]
De acuerdo, se dejó como un _guiño_ pero se quita sin problema

**Comment by minuscorp** [comment]
Fixed in https://github.com/minuscorp/ebikemotion2/pull/420/commits/4820efe245e522054477fed3bc020fa6a8f9827b
