### ISSUE TITLE
Cambio Nombre Ruta por Defecto

### ISSUE THREAD

**Issue by jonstm** [bisite/Ebikemotion2-iOSFeedback#2]
## Platform Information

* Application:

> - [X] Ebikemotion 2

* Version: 1.0.2

* Build Number: 687.170320

* Source:

> - [X] Buddybuild

* Device: iPhone 6

* iOS Version:  iOS 10.2.1

* Internet Connectivity: 4G

* iWoc Firmware Version (if any): 

> - [ ] CAN
> - [ ] 485

## Current Behavior
cuando salvas varias rutas, es "pesado" el tener que borrar la cadena de caracteres que sale por defecto como nombre de la actividad. 

## Possible Solution
Que al pulsar encima para darle un nombre, se borre el texto que hay, o que se seleccione automaticamente todo el texto que hay para que con la siguiente pulsación se borre de una vez.

**Comment by minuscorp** [comment]
Fixed in https://github.com/minuscorp/ebikemotion2/pull/420/commits/ae7ad140dc955529680437f567cdda223b1ac3ae
