### ISSUE TITLE
Aviso Error Emparejado en "settings"

### ISSUE THREAD

**Issue by jonstm** [bisite/Ebikemotion2-iOSFeedback#3]
## Platform Information

* Application:

> - [X] Ebikemotion 2

* Version: 1.0.2

* Build Number: 687.170320

* Source:

> - [X] Buddybuild

* Device: iPhone 6

* iOS Version:  iOS 10.2.1

* Internet Connectivity: 4G

* iWoc Firmware Version (if any): 

> - [ ] CAN
> - [ ] 485

## Current Behavior
Cuando no se empareja el iWoc automáticamente y vas a el menu de "settings" y luego a "Pair with..." si por lo que sea no se pudo emparejar, no da ningun tipo de error o aviso y tiendes a pulsar varias veces... sin saber exactamente que está pasando o que es lo que falla

## Possible Solution
Sacar un aviso de que no se pudo establecer la conexión y si fuese posible indicar el motivo (no se encontró el dispositivo, el dispositivo ya está emparejado con otro equipo...)

**Comment by minuscorp** [comment]
Técnicamente no es ése el propósito del botón. Como su nombre indica `Pair with new ebike` lo que hace es borrar la última bicicleta conectada (y si hay alguna conectada actualmente, desconectarla) e intentar emparejarse con cualquier bicicleta que haya cerca. No hay éxito o error en el proceso de emparejamiento, si no búsqueda periódica (cada 5 segundos) de iWoc's cercanos e intentos de conexión a los mismos.

**Comment by jonstm** [comment]
El comentario es porque mi manera de actuar fue:
1- Veo que iWoc y App no están conectados
2- Entro en Settings por el iWoc no parpadea en rojo
3- Veo que el estado es "Disconnected"
4- Pulso "Pair with" para tratar de conectar
5- No se que está pasando.

Si el proceso es automático, podíamos  meter algo de animación para saber que ese proceso esta corriendo, propuestas:
   - Un estado intermedio que sea "connecting..."
   - 3 puntos suspensivos al final del "Pair" moviendose
   -  Incluir algún elemento animado de "proceso corriendo/ carga"
   - una cuenta atrás de segundos para saber que algo está haciendo el app.

Creo que seria positivo darlo una vuelta, la que consideréis mejor opción. 

Me pasó varias veces y no terminaba de saber que pasaba. En mi caso enciendo la bici es porque estoy  montado, con el app arrancada y con el pie puesto en el pedal... y esperar los 10 seg a ver si conecta o no hay veces que se hacen largos y tiendo a reiniciar cosas... a ver si acabo antes ;)

**Comment by minuscorp** [comment]
Added in https://github.com/minuscorp/ebikemotion2/commit/6061b6243c10197d57c910d1236f1ff95e6e8c52

**Comment by minuscorp** [comment]
Lo reabro hasta que se incluya en el dealer a través de @pabsanmez

**Comment by minuscorp** [comment]
Added in https://github.com/minuscorp/ebikemotion2dealer/commit/266e99c672bd59f80645e8d3cc170f98c94506de
