### ISSUE TITLE
Fallo Subiendo Ruta -> Se pierde la Ruta

### ISSUE THREAD

**Issue by jonstm** [bisite/Ebikemotion2-iOSFeedback#4]
## Platform Information

* Application:

> - [X] Ebikemotion 2

* Version: 1.0.2

* Build Number: 687.170320

* Source:

> - [X] Buddybuild

* Device: iPhone 6

* iOS Version:  iOS 10.2.1

* Internet Connectivity: 4G

* iWoc Firmware Version (if any): 

> - [ ] CAN
> - [ ] 485

## Current Behavior
Al tratar de salvar una ruta, si no tienes buena cobertura (o datos lentos), se queda un rato en "updating" y llega un momento que se cierra y la ruta desaparece. Entiendo que si no consigue subir la ruta y al paso de un tiempo X cancela el proceso y se pierde la ruta.

## Possible Solution
Dar un aviso de error al guardar la ruta -> reintentar/cancelar

**Comment by minuscorp** [comment]
@jonstm cuando el proceso de subida de ruta no se puede terminar (por las circunstancias que sean, normalmente conectividad) se guarda de manera transparente en la base de datos. Al reabiri la aplicación de cero (esto es, borrándola de las aplicaciones recientes) y volverla a abrir, aparece un toast abajo indicando que se están sincronizando las rutas de nuevo. Ahí aparecerá tu ruta de nuevo 😉

**Comment by jonstm** [comment]
Ok, perfecto esto no lo sabia :D
Lo único veo positivo dar algún tipo de aviso. Tras guardar la ruta, tiendes a mirar tus números que simplemente desaparecen en ese momento... Miras en rutas y tampoco están...

A efectos de experiencia de usuario, creo que se acuerda de la madre de ebikemotion cuando tras hacer una ruta que específicamente has querido grabar y "aparentemente" no está guardada en ningún lado. 

Un usuario normal no va a pensar que tras reiniciar el app, aparecerá. Desde mi punto de vista  pensará que lo perdió y si te pasa 2 veces: desinstalas el APP y deja por escrito tu experiencia en el "market", aunque luego aparezcan por arte de magia.

**Comment by minuscorp** [comment]
Podría ser interesante presentar un mensaje de error más informativo, cuando el fallo es de subida de la ruta. ¿Alguna sugerencia?

**Comment by jonstm** [comment]
Si, esa seria la idea, informar al usuario de que pasó, que su ruta SI está guardada y que tiene que hacer para verla, algo en plan:
 
"La actividad **se guardó correctamente** pero no se pudo cargar en el servidor"
Reinicia la aplicación cuando dispongas de una conexión adecuada para poder visualizarla.

**Comment by minuscorp** [comment]
Lo dejo anotado para añadirlo en cuanto tengamos algo de tiempo, ya que es un añadido menor

**Comment by minuscorp** [comment]
Fixed in https://github.com/minuscorp/ebikemotion2/commit/b127c4ba788590558a4ce7ccf09f7823c85ee792
